### ISSUE TITLE
Cannot find module "rxjs/operators"

### ISSUE THREAD

**Issue by kzanagodev** [Riron/ionic-img-viewer#104]
cli packages: (C:\Users\kevin\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:
    cordova (Cordova CLI) : 7.0.1

local packages:
    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.8.0

System:
    Android SDK Tools : 26.0.2
    Node              : v6.10.3
    npm               : 5.5.1
    OS                : Windows 10

ionic-img-viewer : 
   2.9.0

### Have you checked...
- [ ] That npm install returns no warning ?
- [x ] Doing a purge of your node_modules folder ?

Hi, 

My App crash after installing your plugin. 
I got ' Cannot find module "rxjs/operators" '  error while the app is launching.
If I remove the import of IonicImageViewerModule in app.module.ts and in ngModule entry components the app launch fine.

Do you have any suggestion to fix it ?

Thank you.

**Comment by kzanagodev** [comment]
Fixed by : 
- removing node_modules/rxjs manually 
- reinstall it : npm install rxjs

The operators folder was strangely missing in my node_modules/rxjs folder

**Comment by Whales1992** [comment]
**First Option**
_**According to kzanagodev**_
- Remove node_modules/rxjs manually
- Re-Install rxjs: npm install rxjs
_if this above option did not work, simple follow the second option_

**Second Option** 
- Run this command : find ./node_modules -type d | grep "/rxjs$"
- Remove all the three files displayed like below: 
./node_modules/@reactivex/rxjs
./node_modules/rxjs
./node_modules/zone.js/lib/rxjs
- And run this command: npm install @reactivex/rxjs@5.0.0 (Note: I believe you're using nmp V2 and above)
- Finally Re-run the project.

**Comment by Jasminou** [comment]
no options is working I'm having the same issues here

**Comment by mcabs3** [comment]
my node modules folder has `rxjs/operator` (singular). maybe a typo somewhere?

**Comment by Riron** [comment]
It means that you're not using the right version - `operators` contains pipeable operators.

Please check your dependencies and probably user a lower version of the plugin.

**Comment by mcabs3** [comment]
Yeah, looks like I was able to fix it by installing a newer version of `rxjs`.

`npm i -S rxjs@5.3.3` or higher seems to solve it.

**Comment by touy** [comment]
ERROR in src/app/service.service.ts(6,28): error TS2307: Cannot find module 'rxjs/Operators'.
have the same problem here when I download from git , which it's working fine for windows environment, but not working on centos 6.5

**Comment by woeterman94** [comment]
Got the same issue when trying to build and deploy. 
**TS2307: Cannot find module 'rxjs/Operators'.**
