### ISSUE TITLE
Uncaught Error: Cannot find module "rxjs/operators"

### ISSUE THREAD

**Issue by sreejithmv** [Riron/ionic-img-viewer#101]
### Please provide you version information :
Dependency      |Version
----------------|-------
ionic2          |  3.6.0
angular         | 4.1.3
ionic-img-viewer| ^2.9.0

I am getting following error in console while adding IonicImageViewerModule to imports in app.module.ts

Could you please help me to solve it.

```
vendor.js:134406 Uncaught Error: Cannot find module "rxjs/operators"
    at Object.<anonymous> (vendor.js:134406)
    at __webpack_require__ (bootstrap 846e6f4bdf04c3310b7b:54)
    at Object.<anonymous> (image-viewer.js:1)
    at __webpack_require__ (bootstrap 846e6f4bdf04c3310b7b:54)
    at Object.<anonymous> (index.js:23)
    at __webpack_require__ (bootstrap 846e6f4bdf04c3310b7b:54)
    at Object.<anonymous> (vendor.js:90934)
    at __webpack_require__ (bootstrap 846e6f4bdf04c3310b7b:54)
    at Object.<anonymous> (vendor.js:134370)
    at __webpack_require__ (bootstrap 846e6f4bdf04c3310b7b:54)
```

### Have you checked...
- [x ] That npm install returns no warning ? 
- [x ] Doing a purge of your node_modules folder ?

**Comment by Riron** [comment]
> # Have you checked...
>[x] That npm install returns no warning ?

Are you sure ? 😉 

`2.9.0` works with Ionic `3.9.x` / angular `5.0.x` / RxJS `5.5.x` as only this version of RxJS has exports in `rxjs/operators` with lettable operators.

For Ionic `3.6.0` use `ionic-img-viewer@2.6.x`

**Comment by danigv** [comment]
I'm using ionic-img-viewer 2.8.0 for ionic-angular 3.8.0 and it works fine

**Comment by Riron** [comment]
Yes, `/operators` is used only as of `2.9.0`
